[package]
name = "rs-micros"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
paste = "1.0"
spin = "0.9.8"
riscv = "0.11.1"
ringbuffer = "0.15.0"
cbitmap = "0.3.2"
fdt-parser = "0.4.4"
